server:
  port: 8009

spring:
  application:
    name: config-server


  cloud:
    config:
      label:
        master
      server:
        git:
          uri: https://github.com/haiway2019/springcloudconfig
          username:
          password:
          search-paths:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

